### ISSUE TITLE
#pragma warning (disable:4005) should be at the beginning of the .cpp file

### ISSUE THREAD

**Issue by liubing** [tringi/win32-iocp-events#2]
Currently this warning is suppressed by compiler flags in `.vcxproj` file; if we remove
```
      <DisableSpecificWarnings>4005</DisableSpecificWarnings>
```
the warning would still appear.

**Comment by tringi** [comment]
Well spotted!

I was wondering why the pragma didn't work, but forgot to remove it after changing the compiler option. But it should certainly apply only to the implementation file, not the whole project.
